name: mongodb
url: https://mongodb.com/docs/manual/
path: mongodb.inv
---
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: python3
url: https://docs.python.org/3/
path: python3.inv
---
name: clouddocs
url: https://mongodb.com/docs/atlas/
path: cloud-docs.inv
---
name: compassdocs
url: https://mongodb.com/docs/compass/current/
path: compass-docs.inv
...
